language: php

php:
  - '7.1'
  - '7.2'

env:
  global:
    - COVERAGE=false
    - PHPUNIT_ARGS=''

matrix:
  fast_finish: true
  include:
    - php: '7.2'
      env:
        - COVERAGE=true
        - PHPUNIT_ARGS="--coverage-text"

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

install:
  - travis_retry composer install --no-interaction

script:
  - php vendor/bin/php-cs-fixer fix --config=.cs/.php_cs.php
  - php vendor/bin/phpmd bundle text .cs/md_ruleset.xml
  - php vendor/bin/phpcpd bundle
  - php vendor/bin/phpcbf -n bundle --standard=.cs/cs_ruleset.xml
  - php vendor/bin/phpcs --standard=.cs/cs_ruleset.xml --extensions=php bundle