services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Novactive\Bundle\FormBuilderBundle\Form\Type\:
        resource: '../../Form/Type/*'


    Novactive\Bundle\FormBuilderBundle\Field\FieldTypeFormMapperDispatcher:
        arguments: [!tagged novaformbuilder.fieldtype.mapper]

    Novactive\Bundle\FormBuilderBundle\Field\Mapper\TextLineFormMapper:
        tags: ['novaformbuilder.fieldtype.mapper']

    Novactive\Bundle\FormBuilderBundle\Field\FieldTypeFormMapperDispatcherInterface: '@Novactive\Bundle\FormBuilderBundle\Field\FieldTypeFormMapperDispatcher'
