services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Novactive\Bundle\FormBuilderBundle\Controller\:
        public: true
        resource: '../../Controller/*'

    Novactive\Bundle\FormBuilderBundle\Form\Type\:
        resource: '../../Form/Type/*'

    Novactive\Bundle\FormBuilderBundle\Field\Type\:
        resource: '../../Field/Type/*'

    Novactive\Bundle\FormBuilderBundle\Field\FieldTypeRegistry:
        arguments: [!tagged novaformbuilder.fieldtype]

    Novactive\Bundle\FormBuilderBundle\Controller\:
        resource: "../../Controller/*"
        autowire: true
        autoconfigure: true
        public: false
        exclude: "../../Controller/{Controller}"