services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Novactive\Bundle\FormBuilderBundle\Controller\:
        resource: '../../Controller/*'

    Novactive\Bundle\FormBuilderBundle\Service\:
        resource: '../../Service/*'

    Novactive\Bundle\FormBuilderBundle\Form\Type\:
        resource: '../../Form/Type/*'

    Novactive\Bundle\FormBuilderBundle\Field\Type\:
        resource: '../../Field/Type/*'

    Novactive\Bundle\FormBuilderBundle\Field\FieldTypeRegistry:
        arguments: [!tagged novaformbuilder.fieldtype]