services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Novactive\Bundle\FormBuilderBundle\Core\:
        resource: '../../Core'

    Novactive\Bundle\FormBuilderBundle\Core\FieldTypeRegistry:
        arguments: [!tagged novaformbuilder.fieldtype]

    Novactive\Bundle\FormBuilderBundle\Core\FileUploaderInterface: '@Novactive\Bundle\FormBuilderBundle\Core\FileUploader'