services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Novactive\Bundle\FormBuilderBundle\Controller\:
        resource: '../../Controller/*'

    Novactive\Bundle\FormBuilderBundle\Service\:
        resource: '../../Service/*'

    Novactive\Bundle\FormBuilderBundle\Form\:
        resource: '../../Form/*'

    Novactive\Bundle\FormBuilderBundle\Field\Type\:
        resource: '../../Field/Type/*'

    Novactive\Bundle\FormBuilderBundle\Service\FieldTypeRegistry:
        arguments: [!tagged novaformbuilder.fieldtype]