system:
    default:
        field_templates:
            -   template: "NovaeZFormBuilderBundle:fields:ezcustomform.html.twig"
                priority: 0

        fielddefinition_settings_templates:
            -   template: "NovaeZFormBuilderBundle:platformui/content_type/view:ezcustomform.html.twig"
                priority: 0

        fielddefinition_edit_templates:
            -   template: "NovaeZFormBuilderBundle:platformui/content_type/edit:ezcustomform.html.twig"
                priority: 0

    admin_group:
        field_templates:
            -   template: "NovaeZFormBuilderBundle:fields:ezcustomform_admin.html.twig"
                priority: 10

        fielddefinition_settings_templates:
            -   template: "NovaeZFormBuilderBundle:platformui/content_type/view:ezcustomform.html.twig"
                priority: 10

        fielddefinition_edit_templates:
            -   template: "NovaeZFormBuilderBundle:platformui/content_type/edit:ezcustomform.html.twig"
                priority: 10

    site_group:
        field_templates:
            -   template: "NovaeZFormBuilderBundle:fields:ezcustomform.html.twig"
                priority: 10

        fielddefinition_settings_templates:
            -   template: "NovaeZFormBuilderBundle:platformui/content_type/view:ezcustomform.html.twig"
                priority: 10

        fielddefinition_edit_templates:
            -   template: "NovaeZFormBuilderBundle:platformui/content_type/edit:ezcustomform.html.twig"
                priority: 10
