services:
    nova_ezformbuilder.ezadminui.component.stylesheets:
         parent: EzSystems\EzPlatformAdminUi\Component\TwigComponent
         public: false
         arguments:
            $template: "@@NovaeZFormBuilder/ezadminui/stylesheets.html.twig"
         tags:
             - { name: ezplatform.admin_ui.component, group: 'stylesheet-head' }

    nova_ezformbuilder.ezadminui.component.javascripts:
         parent: EzSystems\EzPlatformAdminUi\Component\TwigComponent
         public: false
         arguments:
             $template: "@@NovaeZFormBuilder/ezadminui/javascripts.html.twig"
         tags:
             - { name: ezplatform.admin_ui.component, group: 'script-body' }

    Novactive\Bundle\eZFormBuilderBundle\Listener\TopMenu:
        arguments:
            - "@translator"
            - '@EzSystems\EzPlatformAdminUi\Menu\MenuItemFactory'
        tags:
            - { name: kernel.event_listener, event: "ezplatform_admin_ui.menu_configure.main_menu", method: "onMenuConfigure" }
