services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Novactive\Bundle\eZFormBuilderBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Novactive\Bundle\eZFormBuilderBundle\Controller\Front\FormController:
        tags: ['controller.service_arguments']
        calls:
        - [setPagelayout, ["$pagelayout$"]]

    Novactive\Bundle\eZFormBuilderBundle\Core\:
        resource: '../../Core'

    # Twig Extensions
    Novactive\Bundle\eZFormBuilderBundle\Twig\Extension:
        tags: ['twig.extension']

    Novactive\Bundle\FormBuilderBundle\Command\MigrateCommand:
        arguments: ['@doctrine.dbal.ezsurvey_connection']