services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Novactive\Bundle\eZFormBuilderBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Novactive\Bundle\eZFormBuilderBundle\Controller\Front\FormController:
        tags: ['controller.service_arguments']
        calls:
        - [setPagelayout, ["$pagelayout$"]]

    Novactive\Bundle\eZFormBuilderBundle\Core\:
        resource: '../../Core'

    # Twig Extensions
    Novactive\Bundle\eZFormBuilderBundle\Twig\Extension:
        tags: ['twig.extension']

    Novactive\Bundle\FormBuilderBundle\Command\MigrateCommand:
        arguments: ['@doctrine.dbal.ezsurvey_connection', '@form_builder.io_service']

    form_builder.io_service:
        class: Novactive\Bundle\eZFormBuilderBundle\Core\IOService
        arguments: ['@form_builder.ezpublish.core.io_service']

    Novactive\Bundle\eZFormBuilderBundle\Core\FileUploader:
        arguments: ['@form_builder.io_service']

    Novactive\Bundle\FormBuilderBundle\Core\FileUploaderInterface: '@Novactive\Bundle\eZFormBuilderBundle\Core\FileUploader'