services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Novactive\Bundle\eZFormBuilderBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Novactive\Bundle\eZFormBuilderBundle\Core\:
        resource: '../../Core'

    # Twig Extensions
    Novactive\Bundle\eZFormBuilderBundle\Twig\Extension:
        tags: ['twig.extension']