services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Novactive\Bundle\eZFormBuilderBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

